imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    states:
        "": ""
        AL: Alabama
        AK: Alaska
        AZ: Arizona
        AR: Arkansas
        CA: California
        CO: Colorado
        CT: Connecticut
        DE: Delaware
        FL: Florida
        GA: Georgia
        HI: Hawaii
        ID: Idaho
        IL: Illinois
        IN: Indiana
        IA: Iowa
        KS: Kansas
        KY: Kentucky
        LA: Louisiana
        ME: Maine
        MD: Maryland
        MA: Massachusetts
        MI: Michigan
        MN: Minnesota
        MS: Mississippi
        MO: Missouri
        MT: Montana
        NE: Nebraska
        NV: Nevada
        NH: New Hampshire
        NJ: New Jersey
        NM: New Mexico
        NY: New York
        NC: North Carolina
        ND: North Dakota
        OH: Ohio
        OK: Oklahoma
        OR: Oregon
        PA: Pennsylvania
        RI: Rhode Island
        SC: South Carolina
        SD: South Dakota
        TN: Tennessee
        TX: Texas
        UT: Utah
        VT: Vermont
        VA: Virginia
        WA: Washington
        WV: West Virginia
        WI: Wisconsin
        WY: Wyoming
        AS: American Samoa
        DC: District Of Columbia
        FM: Federated States Of Micronesia
        GU: Guam
        MH: Marshall Islands
        MP: Northern Mariana Islands
        PW: Palau
        PR: Puerto Rico
        VI: Virgin Islands
        AE: Armed Forces Africa
        AA: Armed Forces Americas
        AE: Armed Forces Canada
        AE: Armed Forces Europe
        AE: Armed Forces Middle East
        AP: Armed Forces Pacific
    days:
        sunday: Sunday
        monday: Monday
        tuesday: Tuesday
        wednesday: Wednesday
        thursday: Thursday
        friday: Friday
        saturday: Saturday
    meeting_types:
        AA: Alcoholics Anonymous
        MA: Marijuana Anonymous
        OA: Overeaters Anonymous
        NA: Narcotics Anonymous

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
