services:
    repository.meeting_type:
        class: Doctrine\Orm\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\MeetingType
    fguillot.client:
        class: JsonRPC\Client
        arguments: ['%treatment_center_api_url%']
    fguillot.client_authenticated:
        class: JsonRPC\Client
        factory: ['@fguillot.client', authentication]
        arguments: ['%treatment_center_user_name%', '%treatment_center_user_password%']
    app.treatment_center_service:
        class: AppBundle\Service\TreatmentCenterService
        arguments: ['@fguillot.client_authenticated', '@repository.meeting_type', '%default_street_address%', '%default_city%', '%default_state%', '%default_zip_code%']


